### ISSUE TITLE
Add response mapping

### ISSUE THREAD

**Issue by DavidMGreen** [apache/incubator-openwhisk-apigateway#18]
Create a response mapping that will allow a sub-field of the body to be moved up to become the body and allow headers to be set to be on the response.

For example: Set response header to `application/xhtml+xml` and set the body to body.result.body.results
```
{
  "type":"respMapping",
  "value":[{
      "action":"insert",
      "from":{
        "value":"application/xhtml+xml"
      },
      "to":{
        "name":"Content-Type",
        "location":"header"
      }
    },
    {
      "action":"transform",
      "from":{
        "location":"body.result.body.results"
      },
      "to":{
        "location":"body"
      }
  }]
}
```
This will allow an OpenWhisk action to return html in the top body layer with the correct headers set.

**Comment by mhamann** [comment]
Yes, you could map things in the same manner if you wanted to.
