### ISSUE TITLE
Create a DAO adapter layer for calls to the datastore

### ISSUE THREAD

**Issue by mhamann** [apache/incubator-openwhisk-apigateway#183]
Currently, the gateway is tightly coupled to redis as a requirement. We want to make this pluggable so that all of the lookups are abstracted through a data layer that can abstract away underlying datastore details.

For example, if someone wanted to replace redis with cassandra or memcached or a filesystem, they could write an adapter for their specific use case and then package it into custom build of the gateway. Eventually, we might even provide multiple drivers in the main build.

Another advantage of this approach is that we can tweak characteristics of the underlying driver without affecting the routing logic directly.

The new flow looks something like this:
`router` -> `DAO` -> `adapter(driver)` (where currently, the driver is redis)

General todos:
- [ ] Add a config flag defining which driver is in use and the parameters it requires
- [ ] Add a DAO layer with functions for things required by routing, subscriptions, etc
- [ ] Write a redis driver that implements the DAO contract and makes the required calls to redis
- [ ] Init the DAO with the selected adapter on startup

**Comment by taylorking** [comment]
![clientsecret](https://cloud.githubusercontent.com/assets/1733912/25201015/71435bf0-251e-11e7-88d6-de4fd752375c.jpeg) 

This flame graph shows that redis.init is quite time consuming. Rather than simply work our current redis interaction code to pass an instance around, we want to make a more robust way to interact with the underlying data store.

**Comment by mhamann** [comment]
We should start thinking about what interface the DAO should expose.

What things do we need to deal with?

- Tenants
- APIs
- Resources (operation / path + index)
- Subscriptions
- Rate limits
- OAuth tokens
- Other stuff needed by policies?

We can add stuff to the list above, but I think it boils down to an interface like this (super rough first pass--don't hold me to it):

```
local _M = {}
function _M.upsertTenant()
function _M.deleteTenant()
function _M.getTenant()
function _M.getTenants()

function _M.createAPI()
function _M.updateAPI()
function _M.deleteAPI()
function _M.getAPI()
function _M.getAPIs(tenant)

function _M.createResource()
function _M.updateResource()
function _M.deleteResource()
function _M.findResource()

function _M.validateRateLimit(resource, { shouldIncrement: true })
```

Rather than splitting things out for oauth tokens and other values that we might need to cache, I think there's probably just a generic cache interface.

```
function _M.cacheSet(key, value)
function _M.cacheGet(key)
function _M.cacheDelete(key)

// OAuth example:
dao.cacheGet('oauth:providers:facebook:tokens:<accessToken>`)
```

**Comment by taylorking** [comment]
#198

**Comment by taylorking** [comment]
for some reason I can't tick the boxes on your issue 

- [x] Add a config flag defining which driver is in use and the parameters it requires
- [/] Add a DAO layer with functions for things required by routing, subscriptions, etc
- [x] Write a redis driver that implements the DAO contract and makes the required calls to redis
- [x] Init the DAO with the selected adapter on startup
