### ISSUE TITLE
Add resolver to discover the dns server for kubernetes

### ISSUE THREAD

**Issue by taylorking** [apache/incubator-openwhisk-apigateway#208]

**Comment by mhamann** [comment]
This needs a description.

**Comment by taylorking** [comment]
[this](https://github.com/openresty/lua-resty-redis/issues/59) is related.. Basically we need a way to inject the kubernetes dns address into the resolver directive in nginx

**Comment by dgrove-oss** [comment]
Closing as obsolete (not an issue for our current kube deployment strategy)
