### ISSUE TITLE
Using API gateway with a redis cluster

### ISSUE THREAD

**Issue by sayanh** [apache/incubator-openwhisk-apigateway#259]
Currently, api gateway works well with a single redis instance. But if we use a cluster of 3 redis instances, api gateway fails to work giving the following error:
`wsk api list                                                   
error: Unable to obtain the API list: Unable to obtain API(s) from the API Gateway (status code 500): {"status":500,"message":"Error: Failed to retrieve APIs: MOVED 2088 1.2.3.4:6379"}`

**Comment by mhamann** [comment]
@sayanh Pull requests are welcome :-)

Will at least need more details around what you are passing in, etc.

**Comment by sayanh** [comment]
I think API gateway is quite impossible to work with redis cluster because of this open issue https://github.com/openresty/lua-resty-redis/issues/102

**Comment by mhamann** [comment]
The recommended approach is to use redis replication and a proxy like twemproxy to handle connecting to the appropriate number of members (also enables sharding, hashing, etc if desired).

Closing this issue.
