### ISSUE TITLE
A list of source files missing Apache license headers

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/incubator-openwhisk-apigateway#273]
Following [Apache license header guideline](http://www.apache.org/legal/src-headers.html), **all human-readable Apache-developed files that are included within a distribution must include the header text with few exceptions**. You can find few exceptions here: [which files do not require a license header](http://www.apache.org/legal/src-headers.html#faq-exceptions).

I used Apache Rat to check this repository after excluding a few files, and I got this report. We need to add Apache licensing header to below files.
```
Unapproved licenses:

  openwhisk-apigateway/tools/build/scanCode.cfg
  openwhisk-apigateway/tools/travis/setup.sh
  openwhisk-apigateway/tools/travis/build.sh
  openwhisk-apigateway/tools/travis/deploy.sh
  openwhisk-apigateway/Dockerfile
  openwhisk-apigateway/Makefile
  openwhisk-apigateway/DEPENDENCIES.md
  openwhisk-apigateway/tests/run-tests.sh
  openwhisk-apigateway/tests/install-deps.sh
  openwhisk-apigateway/build_profiling.sh
  openwhisk-apigateway/doc/v1/policies.md
  openwhisk-apigateway/doc/v1/management_interface_v1.md
  openwhisk-apigateway/doc/v1/security.md
  openwhisk-apigateway/doc/profiling.md
  openwhisk-apigateway/doc/v2/management_interface_v2.md
```
The excluded files are:
```
**/*.json
**/**.gradle
**/gradlew
**/gradle/**
**/.**
**/templates/**
**/*.j2.*
**/.github/**
**/auth.whisk.system
**/auth.guest
**/i18n_resources.go
```

**Comment by mhamann** [comment]
@daisy-ycguo is there an automated tool to add those license headers?

**Comment by daisy-ycguo** [comment]
@mhamann Apache Rat could do that, yet still need a human verification.

**Comment by mrutkows** [comment]
@daisy-ycguo is your exclusion list specific to this repo.? or is it a general list for all repos?  If that is the case, we should track the general exclusion in a tracking Issue under the "release" repo. and perhaps submit a specific issue to scancode (i.e, utilities repo) which we link in the tracking issue.  We should discuss the general exclusion list in detail.

**Comment by mrutkows** [comment]
Also, I am removing the local copy of scancode.cfg in this PR https://github.com/apache/incubator-openwhisk-apigateway/pull/289

**Comment by mrutkows** [comment]
In PR https://github.com/apache/incubator-openwhisk-apigateway/pull/293/files, Dragos removed Adobe from the following files  

- openwhisk-apigateway/Dockerfile 
- api-gateway.conf
- conf.d/api_gateway_init.conf
- conf.d/api_gateway_logging.conf
- conf.d/blacklist.conf
- conf.d/commons/common-headers.conf
- conf.d/default.conf
- conf.d/includes/analytics_endpoints.conf
- conf.d/includes/basic_endpoints.conf
- html/index.html
- tests/test_initialization.t

PR [](https://github.com/apache/incubator-openwhisk-apigateway/pull/292/files), Matt updated the following files:
- 


PR [](https://github.com/apache/incubator-openwhisk-apigateway/pull/296/files), Matt updated the following files:
- conf.d/managed_endpoints.conf
- conf.d/management_apis.conf

**Comment by mrutkows** [comment]
Closing this issue and will open more granular issues for any remaining files that need to have ASF headers added.
