### ISSUE TITLE
Fix the copyryright IBM issue in the headers

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-apigateway#294]
This is one example:
https://github.com/apache/incubator-openwhisk-apigateway/blob/master/conf.d/managed_endpoints.conf#L2,
https://github.com/apache/incubator-openwhisk-apigateway/blob/master/conf.d/management_apis.conf#L2
Still keep an eye on other files to see if there is still the same copyright left.

**Comment by houshengbo** [comment]
@daisy-ycguo Could you take care of this issue?

**Comment by daisy-ycguo** [comment]
I think the license header is not Apache 2. Should we change it to Apache 2 ?

**Comment by houshengbo** [comment]
Yes

**Comment by bdelacretaz** [comment]
> If we decide to donate everything, we can only keep the apache license without IBM copyright.

What do you mean by that, is there code in Apache repositories that you think has not been donated to the ASF?

**Comment by csantanapr** [comment]
All source code currently in all the ASF repos that came from IBM is donated to ASF.

**Comment by houshengbo** [comment]
This issue has been closed, since all the headers have been changed to the Apache header.
