### ISSUE TITLE
awk script in init.sh matches wrong lines in /etc/resolv.conf

### ISSUE THREAD

**Issue by baxtersa** [apache/incubator-openwhisk-apigateway#312]
I'm on RHEL 7.5, and my `/etc/resolv.conf` file contains the following comment

> \# NOTE: the libc resolver may not support more than 3 nameservers.
> \# The nameservers listed below may not be recognized.

**Expected Behavior**

The `awk` script in `init.sh` matches only lines of the pattern `nameserver <ip-address>`.

**Actual Behavior**

The `awk` script matches both lines in the comment, injecting invalid syntax into the generated `conf.d/includes/resolvers.conf` file:

```bash
$ cat conf.d/includes/resolvers.conf
resolver <ip-address> <ip-address> <ip-address> NOTE: The <ip-address>;
```

**Proposed Solution**

In `init.sh`, the `awk` command matches lines containing the string `nameserver`

```bash
echo resolver $(awk 'BEGIN{ORS=" "} /nameserver/{print $2}' /etc/resolv.conf [...]
```

This should be changed to only match lines _beginning_ with the string `nameserver`

```bash
echo resolver $(awk 'BEGIN{ORS=" "} /^nameserver/{print $2}' /etc/resolv.conf [...]
```

I'm happy to open up a PR with this minor change if people agree with it.

**Comment by mrutkows** [comment]
@baxtersa I think that we would welcome a PR as this is clearly not intended behavior.  Thanks!

**Comment by mhamann** [comment]
Thanks for the issue and PR! Nice catch. Merged!
