### ISSUE TITLE
Build broken. Alpine linux no longer contains jemalloc and jemalloc_dev

### ISSUE THREAD

**Issue by larandersson** [apache/incubator-openwhisk-apigateway#334]
Since a couple of weeks, the build is broken. It fails with the following error:
```
ERROR: unsatisfiable constraints:
  jemalloc (missing):
    required by: world[jemalloc]
  jemalloc-dev (missing):
    required by: world[jemalloc-dev]
```
The reason for this is that these libraries no longer are included in alpine since v 3.9.

**Comment by larandersson** [comment]
@mhamann I tested today to build the image against alpine:latest (v 3.9) with talloc instead of jemalloc and the build succeeds, as well as the unit tests. I also tested to list apis and invoke apis through the gateway, which also worked as before.

**Comment by dgrove-oss** [comment]
@mhamann or @mdeuser  -- please take a look at this.

**Comment by mdeuser** [comment]
@alexsong93 - do you know of any need for this specific malloc implementation (jemalloc) ?

**Comment by mhamann** [comment]
Apologies for the delay @dgrove-oss and @larandersson. Been slammed recently.

I have a fix in the works for this. Jemalloc is probably the most ideal candidate package, but is only used as part of the profiling run, so it can be removed from the main Dockerfile. I'll PR a fix for that and the profiling build here shortly.
